
project_id = "qdttapddgbzmmxhbmbfl"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[storage]
enabled = true

[auth]
enabled = true

[functions]
[functions.analyze-web3]
verify_jwt = true
[functions.create-checkout]
verify_jwt = true
[functions.stripe-webhook]
verify_jwt = false
[functions.create-share]
verify_jwt = true
[functions.get-shared-roast]
verify_jwt = false
